# use an existing docker image as base
FROM node:alpine
WORKDIR /usr/app

# Downlaod and install dependency
COPY package.json .
RUN npm install
COPY ./ ./



#  Tell the image what to do when it starts as container
CMD ["npm","run","start"]
